name: docker-pr-action
on:
  pull_request:
    branches:
       - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag-my-image-name:$(date +%s)