name: push-image-to-dockerhub
on:
  pull_request:
    branches:
      - 'main'

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  REPO_NAME: ${{ github.repository }}

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}